import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Sora, Inter } from "next/font/google";
import RexGalaxyNavbar from "../../components/navbar";
import CustomCursor from "../../components/customCursor";
import Footer from "../../components/footer"
import BottomStickyForm from "../../components/bottombar";
// import ContactSidebar from "@/components/ContactSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const sora = Sora({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["400", "500", "600", "700"],
});


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sora.variable} ${inter.variable} antialiased`}
      >
        <RexGalaxyNavbar/>
        <CustomCursor/>
        {/* <ContactSidebar/> */}
        {children}
        <Footer/>
        <BottomStickyForm/>
      </body>
    </html>
  );
}
